# Generated by Django 4.2.6 on 2023-12-04 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_App', '0002_club_delete_proyecto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='correo',
            field=models.EmailField(max_length=254),
        ),
    ]
