# Generated by Django 4.2.6 on 2023-12-04 01:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_App', '0003_alter_club_correo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='añonacimiento',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='club',
            name='estado',
            field=models.CharField(choices=[('vigente', 'VIGENTE'), ('suspendido', 'SUSPENDIDO'), ('retirado', 'RETIRADO')], max_length=50),
        ),
        migrations.AlterField(
            model_name='club',
            name='nombresocio',
            field=models.CharField(max_length=200, validators=[django.core.validators.MaxLengthValidator(80)]),
        ),
        migrations.AlterField(
            model_name='club',
            name='sexo',
            field=models.CharField(choices=[('hombre', 'HOMBRE'), ('mujer', 'MUJER'), ('no binario', 'NO BINARIO')], max_length=50),
        ),
    ]
